/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Grtgbe } from "./Grtgbe";
import { GrtgbeCountArgs } from "./GrtgbeCountArgs";
import { GrtgbeFindManyArgs } from "./GrtgbeFindManyArgs";
import { GrtgbeFindUniqueArgs } from "./GrtgbeFindUniqueArgs";
import { DeleteGrtgbeArgs } from "./DeleteGrtgbeArgs";
import { GrtgbeService } from "../grtgbe.service";
@graphql.Resolver(() => Grtgbe)
export class GrtgbeResolverBase {
  constructor(protected readonly service: GrtgbeService) {}

  async _grtgbesMeta(
    @graphql.Args() args: GrtgbeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Grtgbe])
  async grtgbes(@graphql.Args() args: GrtgbeFindManyArgs): Promise<Grtgbe[]> {
    return this.service.grtgbes(args);
  }

  @graphql.Query(() => Grtgbe, { nullable: true })
  async grtgbe(
    @graphql.Args() args: GrtgbeFindUniqueArgs
  ): Promise<Grtgbe | null> {
    const result = await this.service.grtgbe(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Grtgbe)
  async deleteGrtgbe(
    @graphql.Args() args: DeleteGrtgbeArgs
  ): Promise<Grtgbe | null> {
    try {
      return await this.service.deleteGrtgbe(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
